server:
  servlet:
    context-path: /pdf
  port: 8090
spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:sqlite:./etc/databases/generated_pdfs.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework: INFO
    com:
      tu2l:
        pdf: DEBUG
  file:
    name: ./etc/logs/pdf-service/app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 1
