server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/user/**
          filters:
          - StripPrefix=1
        
        - id: pdf-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/pdf/**
          filters:
            - StripPrefix=1
gateway: # Custom gateway configuration
  public-routes:
    - /api/user/auth/**
    - /api/pdf/**

# Common configuration
logging:
  level:
    org:
      springframework: INFO
    com:
      tu2l:
        pdf: DEBUG
  file:
    name: ./../etc/logs/gateway-service/app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 1