server:
  port: 8080

gateway: # Custom gateway configuration
  public-routes:
    - /api/users/auth/**
    - /api/pdf/**
  service-urls:
    user-service: http://localhost:8091
    pdf-service: http://localhost:8090

# Common configuration
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
        web: DEBUG
    com:
      tu2l:
        gateway: DEBUG
        pdf: DEBUG
    reactor:
      netty: INFO
  file:
    name: ./etc/logs/gateway-service/app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 1

jwt:
  secret-key: ${JWT_SECRET_KEY:dev-secret-key-must-be-at-least-256-bits-or-32-characters-long}
  access-token:
    expiration-minutes: 15
  refresh-token:
    expiration-days: 7
  issuer: resume-builder-app
