server:
  port: 8080

gateway: # Custom gateway configuration
  public-routes:
    - /api/user/auth/**
    - /api/pdf/**
  service-urls:
    user-service: http://localhost:8091
    pdf-service: http://localhost:8090

# Common configuration
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
        web: DEBUG
    com:
      tu2l:
        gateway: DEBUG
        pdf: DEBUG
    reactor:
      netty: INFO
  file:
    name: ./etc/logs/gateway-service/app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 1

jwt:
  secret-key: 6594c507-2129-4ae7-a569-ed54e00ca66b
  access-token:
    expiration-minutes: 15
  refresh-token:
    expiration-days: 7
  issuer: resume-builder-app
