server:
  servlet:
    context-path: /user
  port: 8091
spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
logging:
  level:
    org:
      springframework: INFO
    com:
      tu2l:
        user: INFO
  file:
    name: ./logs/user-service/app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 1
jwt:
  secret-key: yourSecureSecretKeyAtLeast32CharactersLong
  access-token:
    expiration-minutes: 30
  refresh-token:
    expiration-days: 1
  issuer: resume-builder-app
